$url = 'http://downloads.ghostscript.com/public/gs915w32.exe'
$url64 = 'http://downloads.ghostscript.com/public/gs915w64.exe'
$uninstallRegKey = 'HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\GPL Ghostscript 9.15'
$version = [Version] '9.15'
$package = 'Ghostscript.app'
