name: Package Bug Report
description: Something went wrong with the installation of a package? Or did you find an unexpected behavior?
title: "(packageName) "
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Do NOT report Security related issues here, instead use the Report Abuse on the package page instead. See https://docs.chocolatey.org/en-us/information/security#report-issue**.

        Thank you for taking the time to fill out this bug report! Please fill out out the necessary information as complete as you can. Remember, it is better to include too much information, than too little. Additionally, make sure that the issue title starts with the name of the package you were seeing the issue with inside paranthesis (e.g. `(putty)`).
  - type: checkboxes
    attributes:
      label: Checklist
      description: Before continuing, make sure that you have done the following.
      options:
        - label: I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.
          required: true
        - label: I have verified that this is happening in the latest available version of the package.
  - type: dropdown
    id: choco-version
    attributes:
      label: Chocolatey Version
      description: |
        What version of Chocolatey do you have installed on the machine where this bug occurred (check all versions that apply, if there are any other versions you know of that are affected please add this to the Additional Details box further down)?
        Do mind that versions older than the latest version that was available 1 year ago will not be supported.
      multiple: true
      options:
        - 2.3.0
        - 2.2.2
        - Other (note in the comments)
    validations:
      required: true
  - type: dropdown
    id: choco-license
    attributes:
      label: Chocolatey License
      description: |
        Select the license that you are using for Chocolatey when you discovered this bug (Open Source users should select None).
      options:
        - Professional
        - Business
        - Architect
        - MSP
    validations:
      required: false
  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: |
        Which version of the package did you find this bug for?
      placeholder: ex 5.0.0 or 4.0.0 -> 4.1.0 for upgrades.
    validations:
      required: true
  - type: textarea
    id: current-behaviour
    attributes:
      label: Current Behaviour
      description: Please provide a concise description of what you are experiencing.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: Please provide a concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: |
        How can we reproduce the behaviour that you are seeing, please include the exact steps that is needed.
        If no steps are included, and we are unable to reproduce the issue it may be closed without notice.
      placeholder: |
        1. In this environment...
        2. Run '...'
        3. See error...
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        What environment did you encounter the bug in? Operating System, .NET Version, PowerShell Version and the shell/terminal emulator used (ie. PowerShell, CMD).

        NOTE: _PowerShell Core is not supported_.

        TIP:
        - To get the Operating System, run `[System.Environment]::OSVersion.ToString()` in a PowerShell session.
        - To get the PowerShell Version, run `$PSVersionTable` in a PowerShell session.
      value: |
        - Operating System:
        - PowerShell Version:
        - Shell:
      render: markdown
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Chocolatey Log
      description: |
        Include the log that has been created by Chocolatey. If possible, it is prefered that this be a link to a file located at https://gist.github.com instead of embedded directly inside the issue. Remember to remove any **sensitive information** from the log before posting.

        Tip: For standard installations, the Chocolatey log file is located at `C:\ProgramData\chocolatey\logs\chocolatey.log`.
      render: shell
    validations:
      required: true
  - type: textarea
    id: additional-details
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering?

        Tip: You can attach images by clicking this area to highlight it and then drag files in.
    validations:
      required: false
