$url = 'http://downloads.ghostscript.com/public/gs910w32.exe'
$url64 = 'http://downloads.ghostscript.com/public/gs910w64.exe'
$uninstallRegKey = 'HKLM:SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\GPL Ghostscript 9.10'
$version = [Version] '9.10'
$package = 'Ghostscript.app'
